apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/bitnami/nginx
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /opt/bitnami/nginx/html/
              name: nginx-docs
      volumes:
        - name: nginx-docs
          configMap:
            name: nginx-docs-cm