apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cooking-ingress
spec:
  rules:
    # host to be found in your cluster config
    - host: {{ .Values.app.ingress.host}}.{{ .Values.app.ingress.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80